import React from "react";
import ReactDOM from "react-dom";
//import App from "./App";
import Student from "./Student";
import App from "./App";
import spark from "./Student";
import Eh from "./Student";
import student1 from "./student1";
//let e1 = <h1>Hello Spark </h1>;
//ReactDOM.render(e1, document.getElementById("root"));
//ReactDOM.render(<App />, document.getElementById("root"));
//ReactDOM.render(<Student name="dilu" />,document.getElementById("noob"));
ReactDOM.render(<App/>,document.getElementById("root"));
//ReactDOM.render(<Eh />,document.getElementById("root"));
//ReactDOM.render(<student1 />,document.getElementById("root"));
